### PR TITLE
8685dwdgy adding a disclaimer for safari and IE users

### PR DESCRIPTION
**Pull request by sab-LC**
**[Issue:](https://app.clickup.com/t/8685dwdgy)**

- Adding a dropdown/banner disclaimer for unsupported browsers until we can establish support.

**Solution:**
- Detect whether a user is using IE/safari and based on that bring up a a dropdown/banner disclaimer for unsupported browsers.

**Screen Shot:**
- Safari:

image

- IE:

image

- IF sandbox banner is present:

image

### CODE REVIEW

**Comment by birbjam** [comment]
This is great, but I want to make sure that banner will not interfere with the sandbox yellow banner that reminds the user they are on the test site before I approve this PR.

Screenshot 2023-10-16 at 10 08 32 AM

**Review by lc-hd — APPROVED** [review]

**Review by birbjam — CHANGES_REQUESTED** [review]
I tested this with Safari:

Screenshot 2023-10-17 at 10 05 19 AM

Screenshot 2023-10-17 at 10 10 15 AM

Screenshot 2023-10-17 at 10 09 30 AM



1. Navigation is obscured by the sandbox banner.
2. Depending on the size of the window, the IE/Safari Banner moves, being either on top of the cookie banner or halfway on the page.
3. Clicking on "Got it!" does not make the banner go away.

**Comment by sab-LC** [comment]
> I tested this with Safari:
> 
> Screenshot 2023-10-17 at 10 05 19 AM
> 
> Screenshot 2023-10-17 at 10 10 15 AM
> 
> Screenshot 2023-10-17 at 10 09 30 AM
> 
> 1. Navigation is obscured by the sandbox banner.
> 2. Depending on the size of the window, the IE/Safari Banner moves, being either on top of the cookie banner or halfway on the page.
> 3. Clicking on "Got it!" does not make the banner go away.

On my end, I am not facing the issue 2-3. Although issue 1 is there and it is in the develop branch not in this branch explicitly, can you please take the fresh pull and verify again?

**Comment by birbjam** [comment]
> 
> On my end, I am not facing the issue 2-3. Although issue 1 is there and it is in the develop branch not in this branch explicitly, can you please take the fresh pull and verify again?

I cleared my cache and did a pull and it's still the same.

**Comment by lc-hd** [comment]
On my machine, it is working. The only thing is clicking the `Got It` button didn't make the notification disappear. I've attach a video of my experience. 

https://github.com/biocodellc/localcontexts_db/assets/145378945/04416abd-7396-4e16-b87b-8d52987877f3

**Review by arojas1 — CHANGES_REQUESTED** [review]
In Edge I get a similar issue. "Got it!" doesn't make the banner disappear and only the cookie banner appears at the bottom of the screen. I have to scroll to the bottom of the page to see the IE warning banner.

Without scrolling:
image

After scrolling to the bottom:
image

Full page screenshot:
image

**Comment by birbjam** [comment]
- Now it looks like it's supposed to but when I click on the button nothing happens, the banner only disappears when I click on the button AND refresh the page manually.

Screenshot 2023-10-18 at 2 41 03 PM

- There's also still the issue of the orange banner obscuring the header's navigation.
Screenshot 2023-10-18 at 2 41 55 PM

Expected behavior: 
https://github.com/biocodellc/localcontexts_db/assets/41635757/f1d3579f-1c71-418a-8896-3f2dd0689ff7

**Review by birbjam — CHANGES_REQUESTED** [review]
See above comment

**Comment by lc-hd** [comment]
I just tried and clicking the `Got It` button now closes the notification.

https://github.com/biocodellc/localcontexts_db/assets/145378945/56d9f55a-019e-4389-9813-11b8a1a7c04a

**Comment by arojas1** [comment]
> In Edge I get a similar issue. "Got it!" doesn't make the banner disappear and only the cookie banner appears at the bottom of the screen. I have to scroll to the bottom of the page to see the IE warning banner.
> 
> Without scrolling: image
> 
> After scrolling to the bottom: image
> 
> Full page screenshot: image

Not sure if it's because I am using my local to view these changes but the same thing is happening on Edge still. (Cleared history and cache)

**Comment by arojas1** [comment]
Tried again and looks like on Microsoft Edge the popup isn't showing anymore but using IE it works properly (at the top of the page and dismissable). Since IE is no longer supported by Microsoft, I would suggest still adding Edge as one that may have issues but other than that it looks good.

**Comment by sab-LC** [comment]
> Tried again and looks like on Microsoft Edge the popup isn't showing anymore but using IE it works properly (at the top of the page and dismissable). Since IE is no longer supported by Microsoft, I would suggest still adding Edge as one that may have issues but other than that it looks good.

Hey Ashley, I have now added Edge in the list also with IE and Safari.

**Review by birbjam — APPROVED** [review]
Looks good now, thanks!

**Pull request merged**
