### PR TITLE
8685dwg3e invite-user

### PR DESCRIPTION
**Pull request by lc-hd**
This code creates a modal for inviting new users from the community members page.

 **Demo of back functionality** 
[video](https://github.com/biocodellc/localcontexts_db/assets/145378945/42f30136-62e3-4001-b0cf-87f1f3826b7a)

**Demo inviting a new user**
[video](https://github.com/biocodellc/localcontexts_db/assets/145378945/a81d0e7e-04e3-404d-819e-6a9d59a6f540)

**Demo inviting a preexisting user**
[video](https://github.com/biocodellc/localcontexts_db/assets/145378945/62b925f9-1154-4ba4-867a-0d1430644c0b)

----------------
Since these changes modified the original invite user view. 
I included a demo that shows that functionality still works.

**Demo of no regression**
[video](https://github.com/biocodellc/localcontexts_db/assets/145378945/94b65454-32cc-421c-be30-0a8c9744fc9f)

### CODE REVIEW

**Review by birbjam — APPROVED** [review]
I will check in with Renee to see if we have a Figma for this bit and later we can update the UI but for now this looks good.

**Review by sab-LC — APPROVED** [review]
I believe that the invite notifications will look more appealing if we show them in an alert box, instead in the same section. As Diana mentioned we can update the UI later. For now, this is good.

**Comment by arojas1** [comment]
Looks like the input fields are only showing on the Community invite member side for the modal but not the Institution invite member side.

Institution view:
image

Community view:
image

**Comment by lc-hd** [comment]
Thank you @arojas1 , I'll push an update so the new fields show up on the Institution Invite member side

**Pull request merged**
